# -*- coding: utf-8 -*-
"""
Created on Sun Mar 28 22:04:59 2021

@author: shital
"""
import tkinter
top=tkinter.Tk()
print('Welcome to 2021 Horoscope')
s=input('Please your zodiac sign to know your horoscope:')
sign=str.lower(s)
if sign=='aquaris':
    print('Element: Air\nPolarity: Positive\nRuling Planet: Uranus\nRuling House: Eleventh\nSpirit Color: Sky blue\nLucky Gem: Amethyst\nFlower: Orchid\nTop Love Matches: Sagittarius')
    print('Here is your horoscope:\nIndependent and enigmatical, Aquarians are unique. There is no one quite like an Aquarius, and because each is so incredibly individual, it can be tough to describe them as a group. Aquarians do not like labels, and may shy away from any adjective—even the good ones you might bestow upon them. Aquarians believe in the nature of change and evolution, and even though they are a fixed sign, they may not necessarily believe they are the same people they were when they were born.')
elif sign=='sagittarius':
    print('Element: Fire\nPolarity: Positive\nQuality: Mutable\nRuling Planet: Jupiter\nRuling House: Ninth\nSpirit Color: Light Blue\nLucky Gem: Topaz\nFlower: Carnations & crocuses\nTop Love Matches: Aquaris')
    print('Here is your horoscope:\nIndependent and strong-willed, Sagittarius personalities are all about going off the beaten path. Sagittarius isn’t afraid to step away from the pack, and is a natural born leader who goes after what he or she wants, regardless of what other people think. Sagittarius is a born adventurer, and loves solo travel and exploration. Sagittarius also loves exploring the inner workings of their minds, and love stretching their horizons through a good book or movie.')
elif sign=='taurus':
    print('Element: Earth\nPolarity: Negative\nQuality: Fixed\nRuling Planet: Venus\nRuling House: Second\nSpirit Color: Pink\nLucky Gem: Emerald\nFlower: Rose, Poppy, & Foxglove\nTop Love Matches: Cancer & Virgo')
    print('ere is your horoscope:\nSmart, ambitious, and trustworthy, Taurus is the anchor of the Zodiac. Amazing friends, colleagues, and partners, Taureans value honesty above all else and are proud that their personal relationships tend to be drama free. Bulls get the reputation of being stubborn, but they are not always stuck in their ways. This searching sign is willing to see another point of view, but they will not flip-flop on an opinion just to make someone else happy. They will shift their thinking only if they truly have a change of heart.')
elif sign=='virgo':
    print('Element: Earth\nPolarity: Negative\nQuality: Mutable\nRuling Planet: Mercury\nRuling House: Sixth\nSpirit Color: Silver\nLucky Gem: Peridot\nFlower: Sunflower & marigold\nTop Love Matches: Cancer')
    print('Here is your horoscope:\nSmart, sophisticated, and kind, Virgo gets the job done without complaining. Virgos are amazing friends, always there to lend a hand and also lend advice. Practical Virgos are incredibly adept at big picture thinking, and planning out their life, their vacations, and what they are going to do today is not a drag it makes them feel in control and secure.')
elif sign=='gemini':
    print('Element: Air\nPolarity: Positive\nQuality: Mutable\nRuling Planet: Mercury\nRuling House: Third\nSpirit Color: Yellow\nLucky Gem: Tiger Eye & Emerald\nFlower: Lavender & Lily of the Valley\nTop Love Matches: Aries & Leo')
    print('Smart, passionate, and dynamic, Gemini is characterized by the Twins, Castor and Pollux, and is known for having two different sides they can display to the world. Expert communicators, Gemini is the chameleon of the Zodiac, adept at blending into different groups based on the vibe and energy they perceive. While they are also amazing at showcasing surface traits, the Gemini well runs deep, which is why the Twins are one of the Zodiac is most emotionally intelligent signs.')
elif sign=='pisces':
    print('Element: Water\nPolarity: Negative\nQuality: Mutable\nRuling Planet: Neptune\nRuling House: Twelfth\nSpirit Color: Sea green\nLucky Gem: Moonstone\nFlower: Water lily\nTop Love Matches: Virgo')
    print('Here is your horoscope:\nSmart, creative, and deeply intuitive, Pisces can be close to psychic. Pisces feel things deeply, and have incredibly strong gut reactions. A Pisces "knows" things from deep within, and can often judge whether a person or situation is good or bad. That does not mean a Pisces ignores the logical part of their brain, though. Deeply intelligent, Pisces have a profound respect for the power of the human mind. Is it a surprise that Albert Einstein was a Pisces?\nPisces signs are sensitive, and get along well in small groups of people. Sometimes, a Pisces may feel like they have an internal and external self, and they may need to spend a lot of time solo to recalibrate those two halves of themselves. A Pisces is rarely lonely when they are by themselves, and have an active imagination. Creative, Pisces love spending time reading, exploring or creating art or music, and understanding their emotions through art.')
elif sign=='capricorn':
    print('Element: Earth\nPolarity: Negative\nQuality: Cardinal\nRuling Planet: Saturn\nRuling House: Tenth\nSpirit Color: Dark blue\nLucky Gem: Lapis lazuli\nFlower: Pansy\nTop Love Matches: Virgo')
    print('Here is your horoscope:\nmart, hardworking, and fully in control of their destiny, Capricorn signs will always get what they set their mind to, in both personal and professional life—no excuses. Capricorns may get a reputation as stubborn, but they simply know what they want, and also know how they wish other people would behave.\nNatural rule-followers, Capricorns thrive on order and love strict rules, hierarchies, and set ways to do things. Can a Capricorn sign think outside the box? Yes, they can, but they prefer when they have strict boundaries to constrain against—free reign can make them feel paralyzed by choice. Capricorns are great at climbing the corporate ladder, and especially adept at making (and investing) money. Capricorns love family, and put a lot of stock in traditions. A Capricorn might stress themselves out trying to do everything perfectly—a Capricorn may feel like they must present a home-cooked meal every day, and would never admit to doing drive-thru or takeout. ')
elif sign=='aries':
    print('Element: Fire\nPolarity: Positive\nQuality: Cardinal\nRuling Planet: Mars\nRuling House: First\nSpirit Color: Red\nLucky Gem: Diamond\nFlower: Thistle & honeysuckle\nTop Love Matches: Sagittarius')
    print('Here is your horoscope:\nThe first sign of the Zodiac, Aries are the trailblazers. Passionate and independent, Aries will never do something just because everyone else is doing it—a Ram needs to be 100 percent committed to the task at hand. Competitive to the max, the best way to motivate an Aries is to turn something into a contest. Aries will put everything they have (and then some) into winning. Loyal, smart, and impulsive, they always have multiple projects on their mind, and will not be satisfied until their work, social life, and personal lives line up exactly with the dream life they have envisioned. Those who are drawn to magnetic Aries may have trouble keeping up—but if they can, they will have a friend for life.')
elif sign=='cancer':
    print('Element: Water\nPolarity: Negative\nQuality: Cardinal\nRuling Planet: Moon\nRuling House: Fourth\nSpirit Color: Violet\nLucky Gem: Ruby, pearl\nFlower: Orchid and white rose\nTop Love Matches: Taurus & Pisces')
    print('Emotional, intuitive, and practically psychic; ruled by the moon and characterized by the crab, Cancer has so much going on in its watery depths. Cancer signs may seem prickly and standoffish at first meeting, once they make the decision to become friends with someone, that person has a friend for life.\nMost Cancer signs have been called psychic at some point, and with good reason—Cancer can often intuit relationships, ideas, and motivations before anyone has actually spoken. That can make for challenging interactions with this sign—Cancer hates small talk, especially when it contains white lies (like saying, "How nice to see you!" when it is clear that both parties would rather avoid each other). That is why social gatherings can be overwhelming for Cancers. They had much rather spend time in small groups where everyone is on the same page.')
elif sign=='leo':
    print('Element: Fire\nPolarity: Positive\nQuality: Fixed\nRuling Planet: Sun\nRuling House: Fifth\nSpirit Color: Gold\nLucky Gem: Carnelian\nFlower: Sunflower & marigold\nTop Love Matches: Libra')
    print('Here is your horoscope:\nBold, intelligent, warm, and courageous, fire sign Leo is a natural leader of the Zodiac, ready to blaze a trail, vanquish injustice, and make a name for themselves along the way. Blessed with high self-esteem, Lions know that they possess enviable traits—and they are proud of them. They do not believe in false modesty and will be the first to praise themselves for a job well done. But Leo is not self-aggrandizing or unwilling to roll up those sleeves and do the work: this sign knows that in order to be respected and admired, he or she needs to put in the effort worthy of a leader.')
elif sign=='libra':
    print('Element: Air\nPolarity: Positive\nQuality: Cardinal\nRuling Planet: Venus\nRuling House: Seventh\nSpirit Color: Blue\nLucky Gem: Sapphire\nFlower: Rose\nTop Love Matches: Gemini')
    print('Here is your horoscope:\nIntelligent, kind, and always willing to put others before themselves, Libras value harmony in all forms. Ruled by Venus, the planet of beauty, Libra adores a life that looks good. As the master of compromise and diplomacy, Libra is adept at seeing all points of view, and excels at crafting compromises and effecting mediation between others. This sign has a rich inner life yet loves other people, and they are always happiest with a large group of friends, family, and coworkers on whom they can count.\nAn air sign, Libra can often be "up in the clouds," and while he or she is amazing at making big plans, follow through can be tricky.')
elif sign=='scorpio':
    print('Element: Water\nPolarity: Negative\nQuality: Fixed\nRuling Planet: Pluto, Mars\nRuling House: Eighth\nSpirit Color: Black\nLucky Gem: Topaz & opal\nFlower: Hibiscus & geraniums\nTop Love Matches: Cancer')
    print('Here is your horoscope:\nPassionate, independent, and unafraid to blaze their own trail no matter what others think, Scorpio signs make a statement wherever they go. They love debates, are not afraid of controversy, and will not back down from a debate. They also hate people who are not genuine, and are all about being authentic—even if authentic is not pretty.\nBecause of all of these traits, a Scorpio can seem intimidating and somewhat closed off to those who do not know them well. But what people do not realize is that even though Scorpio may seem brusque, as a water sign, they also are very in tune with their emotions, and sometimes may find themselves caught up in their feelings.\nThis leads to Scorpios central conflict: Their feelings are what drives them and strengthens them, but their mutability can scare them and make them feel vulnerable and out of control. Because of this conflict, Scorpios, like their namesake, the scorpion, put up an outer shell and may seem prickly.')
else:
    print('Wrong sign!')
print('\n\nThanks for visiting us!')
top.mainloop()

    